# Generated by Django 3.2.4 on 2021-11-06 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Regent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordercode',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
    ]
