# Generated by Django 3.2.4 on 2021-11-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regent', '0002_alter_category_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.CharField(choices=[('foods', 'foods'), ('beverages', 'beverages')], max_length=12),
        ),
    ]
