# Generated by Django 3.2.4 on 2021-11-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Regent', '0002_alter_order_ordercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Regent.meal'),
        ),
    ]
