# Generated by Django 3.2.4 on 2021-12-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regent', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordercode',
            field=models.IntegerField(null=True),
        ),
    ]
