# Generated by Django 3.2.4 on 2021-11-03 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Regent', '0004_alter_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordercode',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordercode',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ordercode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regent.orderitem'),
        ),
    ]
