# Generated by Django 3.2.4 on 2021-12-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regent', '0004_alter_order_ordercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='ordertype',
            field=models.CharField(max_length=20),
        ),
    ]
