# Generated by Django 3.2.4 on 2021-11-03 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Regent', '0005_auto_20211103_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordercode',
        ),
        migrations.AddField(
            model_name='order',
            name='ordercode',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pick_up_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 15, 14, 6, 435452, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
